
name: quotevault
description: QuoteVault Flutter App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_local_notifications: any
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  timezone: ^0.9.2
  supabase_flutter: ^2.5.6
  flutter_native_timezone: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
